// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241012172754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.ApplicationLogging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogging");
                });

            modelBuilder.Entity("DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(5681),
                            Description = "Łódzkie parki to nie tylko miejsca odpoczynku, ale także świadkowie bogatej historii miasta. Wiele z nich powstało z myślą o mieszkańcach, oferując przestrzeń do rekreacji i bliski kontakt z naturą. Zielone przestrzenie, pełne drzew i ścieżek, zachęcają do spacerów, pikników i aktywnego wypoczynku, a ich różnorodność sprawia, że każdy znajdzie coś dla siebie.",
                            ImagePath = "Resources/Images/Categories/Park_Kategoria_01",
                            ModifiedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(5684),
                            Name = "Parki"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ZoomLevel")
                        .HasColumnType("real");

                    b.HasKey("Id", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(5933),
                            Description = "Wybudowany w latach 1904-1910 wg. projektu Teodora Chrząńskiego pierwotnie nosił nazwę \"Ogród przy ul. Pańskiej\", a w roku 1917 otrzymał imię obecnego patrona Park charakteryzuje się bogatym doborem gatunków roślin oraz zróżnicowanym układem przestrzennym. Od lat 90. prowadzone są prace rewaloryzacyjne, mające na celu przywrócenie parku do jego dawnej świetności oraz dostosowanie go do potrzeb współczesnych użytkowników.",
                            ImagePath = "Resources/Images/Locations/Poniatowski_Park_01",
                            Latitude = 51.754411400000002,
                            Longitude = 19.4423864,
                            ModifiedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(5934),
                            Name = "Park Poniatowski",
                            ZoomLevel = 16.75f
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.PhysicalLocation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AlertEndEventMinutes")
                        .HasColumnType("int");

                    b.Property<int>("AlertStartEventMinutes")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "CategoryId");

                    b.ToTable("PhysicalLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertEndEventMinutes = 0,
                            AlertStartEventMinutes = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(6014),
                            Description = "Nowy tor, stworzony w 2008r. Przeznaczony dla rowerzystów, składa się z trzech sekcji z przeszkodami, w tym dużych skoków dla bardziej zaawansowanych. W zimę teren ten idealnie nadaje się do zjeżdżania na sankach.",
                            ImagePath = "Resources/Images/PhysicalLocations/Bike_Park_01",
                            Latitude = 51.756849000000003,
                            LocationId = 1,
                            Longitude = 19.446677999999999,
                            ModifiedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(6014),
                            Name = "Bike Park",
                            Radius = 75f
                        },
                        new
                        {
                            Id = 2,
                            AlertEndEventMinutes = 0,
                            AlertStartEventMinutes = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(6100),
                            Description = "Most Zakochanych w parku Poniatowskiego stał się romantycznym miejscem, gdzie zakochane pary przypinają kłódki z imionami, symbolizując wieczną miłość. Zwyczaj ten, inspirowany tradycjami z innych miast Europy, polega na wrzuceniu kluczyka do wody po zawieszeniu kłódki, co ma przypieczętować związek. Jest to jedno z najbardziej urokliwych miejsc w Łodzi, idealne na sesję zdęciową.",
                            ImagePath = "Resources/Images/PhysicalLocations/Most_Zakochanych_02",
                            Latitude = 51.753701,
                            LocationId = 1,
                            Longitude = 19.439156000000001,
                            ModifiedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(6100),
                            Name = "Most Zakochanych",
                            Radius = 75f
                        },
                        new
                        {
                            Id = 3,
                            AlertEndEventMinutes = 0,
                            AlertStartEventMinutes = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(6175),
                            Description = "Nowa fontanna w parku Poniatowskiego, typu dry-plaza, jest ceniona przez dzieci jako świetna okazja do schłodzenia się w gorące dni. Umożliwia tworzenie dynamicznych kolorowych efektów wodnych i świetlnych, dzięki podświetleniu LED RGB. Dostępna jest dla mieszkańców od wiosny 2018r. i czynna od maja do września.",
                            ImagePath = "Resources /Images/PhysicalLocations/Fontanna_03",
                            Latitude = 51.754573999999998,
                            LocationId = 1,
                            Longitude = 19.447375000000001,
                            ModifiedDate = new DateTime(2024, 10, 12, 17, 27, 54, 555, DateTimeKind.Utc).AddTicks(6176),
                            Name = "Most Zakochanych",
                            Radius = 50f
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccess.Entities.UserHistory", b =>
                {
                    b.Property<int>("PhysicalLocationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("PhysicalLocationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHistory");
                });

            modelBuilder.Entity("DataAccess.Entities.Location", b =>
                {
                    b.HasOne("DataAccess.Entities.Category", "Category")
                        .WithMany("Locations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.Entities.PhysicalLocation", b =>
                {
                    b.HasOne("DataAccess.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DataAccess.Entities.UserHistory", b =>
                {
                    b.HasOne("DataAccess.Entities.PhysicalLocation", "PhysicalLocation")
                        .WithMany("UserHistory")
                        .HasForeignKey("PhysicalLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User", "User")
                        .WithMany("UserHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("DataAccess.Entities.PhysicalLocation", b =>
                {
                    b.Navigation("UserHistory");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("UserHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
